IF
	InParty(Myself)
	Global("BodhiDead","GLOBAL",1)
	Global("ImoenGainsAbilities","GLOBAL",1)
	PartyRested()
THEN
	RESPONSE #100
		SetGlobal("ImoenGainsAbilities","GLOBAL",2)
		SetGlobalTimer("SBS_NextAbility","GLOBAL",TWO_DAYS)
		Interact([PC])
END

IF
	InParty(Myself)
	Global("BodhiDead","GLOBAL",1)
	Global("ImoenGainsAbilities","GLOBAL",3)
	GlobalTimerExpired("SBS_NextAbility","GLOBAL")
	PartyRested()
THEN
	RESPONSE #100
		SetGlobal("ImoenGainsAbilities","GLOBAL",4)
		Interact([PC])
END

